services:
  kafka:
    image: bitnami/kafka:3.9.0
    restart: always
    ports:
      - "9092:9092"
      - "9094:9094"
    volumes:
      - kafka_data:/bitnami/kafka
    environment:
      KAFKA_CFG_NODE_ID: 0
      KAFKA_CFG_PROCESS_ROLES: controller,broker
      KAFKA_CFG_CONTROLLER_QUORUM_VOTERS: 0@kafka:9093
      KAFKA_CFG_LISTENERS: PLAINTEXT://:9092,CONTROLLER://:9093,EXTERNAL://:9094
      KAFKA_CFG_ADVERTISED_LISTENERS: PLAINTEXT://kafka:9092,EXTERNAL://$KAFKA_SERVER_IP:9094
      KAFKA_CFG_LISTENER_SECURITY_PROTOCOL_MAP: CONTROLLER:PLAINTEXT,EXTERNAL:PLAINTEXT,PLAINTEXT:PLAINTEXT
      KAFKA_CFG_CONTROLLER_LISTENER_NAMES: CONTROLLER
      KAFKA_CFG_INTER_BROKER_LISTENER_NAME: PLAINTEXT
      KAFKA_CFG_CLUSTER_ID: MkU3OEVBNTcwNTJENDM2Qk

  kafka-ui:
    container_name: kafka-ui
    image: provectuslabs/kafka-ui:latest
    ports:
      - 8081:8080
    environment:
      DYNAMIC_CONFIG_ENABLED: 'true'
      KAFKA_CLUSTERS_0_NAME: local
      KAFKA_CLUSTERS_0_BOOTSTRAPSERVERS: kafka:9092
      AUTH_TYPE: "LOGIN_FORM"
      SPRING_SECURITY_USER_NAME: participatevengeance
      SPRING_SECURITY_USER_PASSWORD: $KAFKA_UI_PWD
  #    volumes:
  #      - ~/kui/config.yml:/etc/kafkaui/dynamic_config.yaml

  fulltron-node:
    build:
      context: .
      dockerfile: Dockerfile
    image: tron_fullnode
    ports:
      - 5555:5555
      - 8090:8090
    volumes:
      - ./main_net_config.conf:/java-tron/build/libs/config.conf
      - ./output-directory:/java-tron/build/libs/output-directory
volumes:
  kafka_data: {}