openapi: 3.1.3
info:
  title: Tron Blockchain API
  description: API for interacting with the Tron blockchain.
  version: 1.0.0
servers:
  - url: https://api.trongrid.io
    description: Mainnet API
  - url: https://nile.trongrid.io
    description: Testnet API
paths:
  /wallet/broadcasttransaction:
    post:
      summary: Broadcast a transaction
      description: Broadcast a transaction to the Tron blockchain.
      tags:
        - Transaction
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/Transaction'
      responses:
        '200':
          description: Transaction broadcasted successfully
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/BroadcastTransactionResponse'
        '400':
          description: Invalid request body

  /wallet/createtransaction:
    post:
      summary: Create a transaction
      description: Create a transaction on the Tron blockchain.
      tags:
        - Transaction
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/CreateTransactionRequest'
      responses:
        '200':
          description: Transaction created successfully
          content:
            application/json:
              schema:
                type: string
                # $ref: '#/components/schemas/Transaction'
        '400':
          description: Invalid request body

  # https://developers.tron.network/reference/get-account-info-by-address
  /v1/accounts/{address}:
    get:
      summary: Get account info by address
      description: Get account info by account address
      tags:
        - Account
      parameters:
        - name: address
          in: path
          required: true
          description: owner address in base58 or hex
          schema:
            type: string
      responses:
        '200':
          description: success
          content:
            application/json:
              schema:
                type: object
                properties:
                  data:
                    type: array
                    items:
                      $ref: '#/components/schemas/AccountInfo'
                  success:
                    type: boolean
                  meta:
                    type: object
                    properties:
                      at:
                        type: integer
                        format: int64
                      page_size:
                        type: integer
        '400':
          description: Invalid address format.

  /v1/accounts/{address}/transactions:
    get:
      summary: Get transaction info by account address
      description: Get transaction info by account address
      tags:
        - Account
      parameters:
        - name: address
          in: path
          required: true
          description: owner address in base58 or hex
          schema:
            type: string
        - name: only_confirmed
          in: query
          required: false
          description: Filter by confirmed transactions only
          schema:
            type: boolean
        - name: only_to
          in: query
          required: false
          description: Filter by confirmed transactions only
          schema:
            type: boolean
        - name: only_from
          in: query
          required: false
          description: Filter by confirmed transactions only
          schema:
            type: boolean
        - name: limit
          in: query
          required: false
          description: Filter by confirmed transactions only
          schema:
            type: integer
        - name: min_timestamp
          in: query
          required: false
          description: Filter by confirmed transactions only
          schema:
            type: string
            format: date-time
      responses:
        '200':
          description: success
          content:
            application/json:
              schema:
                type: object
                properties:
                  data:
                    type: array
                    items:
                      $ref: '#/components/schemas/Transaction'
                  success:
                    type: boolean
                  meta:
                    type: object
                    properties:
                      at:
                        type: integer
                        format: int64
                      page_size:
                        type: integer
        '400':
          description: Invalid address format.

components:
  schemas:
    BroadcastTransactionResponse:
      type: object
      properties:
        result:
          type: boolean
        txid:
          type: string
        code:
          type: string
        message:
          type: string
  
    CreateTransactionRequest:
      type: object
      properties:
        owner_address:
          type: string
        to_address:
          type: string
        amount:
          type: integer
          format: int64
        visible:
          type: boolean

    RawData:
      type: object
      properties:
        ref_block_bytes:
          type: string
        ref_block_hash:
          type: string
        expiration:
          type: integer
          format: int64
        data:
          type: string
        timestamp:
          type: integer
          format: int64
        fee_limit:
          type: integer
          format: int64
        contract:
          type: array
          items:
            $ref: '#/components/schemas/Contract'

# https://developers.tron.network/reference/get-account-info-by-address
    AccountInfo:
      type: object
      properties:
        address:
          type: string
        balance:
          type: integer
          format: int64
        create_time:
          type: integer
          format: int64

    # https://developers.tron.network/docs/tron-protocol-transaction
    Transaction:
      type: object
      properties:
        txID:
          type: string
        blockNumber:
          type: integer
        block_timestamp:
          type: integer
          format: int64
        signature:
          type: array
          items:
            type: string
        raw_data_hex:
          type: string
        raw_data:
          $ref: '#/components/schemas/RawData'
        energy_fee:
          type: integer
          format: int64
        energy_usage:
          type: integer
          format: int64
        energy_usage_total:
          type: integer
          format: int64
        net_fee:
          type: integer
          format: int64
        net_usage:
          type: integer
          format: int64
        internal_transactions:
          type: array
          items:
            type: string
        visible:
          type: boolean

    Contract:
      type: object
      properties:
        type:
          type: string
        parameter:
          type: object
          properties:
            value:
              type: object
              properties:
                frozen_balance:
                  type: integer
                  format: int64
                balance:
                  type: integer
                  format: int64
                lock_period:
                  type: integer
                  format: int64
                lock:
                  type: boolean
                unfreeze_balance:
                  type: integer
                  format: int64
                frozen_duration:
                  type: integer
                  format: int64
                amount:
                  type: integer
                  format: int64
                owner_address:
                  type: string
                receiver_address:
                  type: string
                account_address:
                  type: string
                account_name:
                  type: string
                asset_name:
                  type: string
                account_id:
                  type: string
                to_address:
                  type: string
                # type ???
            type_url:
              type: string

    Parameter:
      type: object
      properties:
        type_url:
          type: string
        value:
          $ref: '#/components/schemas/ParameterValue'

    ParameterValue:
      type: object
      properties:
        frozen_balance:
          type: integer
          format: int64
        balance:
          type: integer
          format: int64
        lock_period:
          type: integer
          format: int64
        lock:
          type: boolean
        unfreeze_balance:
          type: integer
          format: int64
        frozen_duration:
          type: integer
          format: int64
        amount:
          type: integer
          format: int64
        owner_address:
          type: string
        receiver_address:
          type: string
        account_address:
          type: string
        account_name:
          type: string
        asset_name:
          type: string
        account_id:
          type: string
        to_address:
          type: string
        # type ???