openapi: 3.0.3
info:
  title: Tron Blockchain API
  description: API for interacting with the Tron blockchain.
  version: 1.0.0
servers:
  - url: https://api.trongrid.io
    description: Mainnet API
  - url: https://nile.trongrid.io
    description: Testnet API
paths:
  /v1/accounts/{address}/transactions:
    get:
      summary: Get transaction info by account address
      description: Get transaction info by account address
      tags:
        - Account
      parameters:
        - name: address
          in: path
          required: true
          description: owner address in base58 or hex
          schema:
            type: string
      responses:
        '200':
          description: success
          content:
            application/json:
              schema:
                type: object
                properties:
                  data:
                    type: array
                    items:
                      $ref: '#/components/schemas/Transaction'
                  success:
                    type: boolean
                  meta:
                    type: object
                    properties:
                      at:
                        type: integer
                        format: int64
                      page_size:
                        type: integer
        '400':
          description: Invalid address format.

components:
  schemas:
    CreateTransactionRequest:
      type: object
      properties:
        extra_data:
          type: string
          description: Extra data to include in the transaction.
        visible:
          type: boolean
          description: Whether the transaction is hex or base58.
        to_address:
          type: string
          description: The recipient's address (base58 format).
        owner_address:
          type: string
          description: The sender's address (base58 format).
        amount:
          type: integer
          description: The amount to transfer in SUN.
      required:
        - to_address
        - owner_address
        - amount

    RawData:
      type: object
      properties:
        ref_block_bytes:
          type: string
        ref_block_hash:
          type: string
        expiration:
          type: integer
          format: int64
        data:
          type: string
        timestamp:
          type: integer
          format: int64
        fee_limit:
          type: integer
          format: int64
        contract:
          type: array
          items:
            type: object
            properties:
              type:
                type: string
              parameter:
                type: object
                properties:
                  value:
                    type: object
                    properties:
                      frozen_balance:
                        type: integer
                        format: int64
                      amount:
                        type: integer
                        format: int64
                      owner_address:
                        type: string
                      to_address:
                        type: string
                  type_url:
                    type: string

    # https://developers.tron.network/docs/tron-protocol-transaction
    Transaction:
      type: object
      properties:
        txID:
          type: string
        blockNumber:
          type: integer
        block_timestamp:
          type: integer
          format: int64
        signature:
          type: array
          items:
            type: string
        raw_data_hex:
          type: string
        raw_data:
          $ref: '#/components/schemas/RawData'
        energy_fee:
          type: integer
          format: int64
        energy_usage:
          type: integer
          format: int64
        energy_usage_total:
          type: integer
          format: int64
        net_fee:
          type: integer
          format: int64
        net_usage:
          type: integer
          format: int64
        internal_transactions:
          type: array
          items:
            type: string
        visible:
          type: boolean